---
version: "2.0"

services:
  pybot:
    image: reecepbcups/hyphacoop_bot:1.0.2
    env:
      - "IN_PRODUCTION=true"
      - "USE_PYTHON_RUNNABLE=true"
      - "RUNNABLE_MINUTES=60"
      - "API_KEY="
      - "API_KEY_SECRET="
      - "ACCESS_TOKEN="
      - "ACCESS_TOKEN_SECRET="
    expose:
      - port: 8080 # just a placeholder
        to:
          - global: true      

profiles:
  compute:
    pybot:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 0.5Gi
        storage:
          size: 1Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        pybot: 
          denom: uakt
          amount: 100


deployment:
  pybot:
    akash:
      profile: pybot
      count: 1